#pragma once

enum MS_AIRCRAFT_RTB_REASON
{
	ARR_Unknown, 
	ARR_Winchester,
	ARR_End_Search_Plan, 
	ARR_Air_Abort,
	ARR_Relieve,
	ARR_Off_Station_Search_Plan,
	ARR_AirMission_Depleted, 
	ARR_UserDefined
};

enum Mars_IconType{
	AMMO_PLANT,     //	弹药工厂
	SSM,     //	地对地导弹
	CIVILIAN,     //	民用的
	BARRACKS,     //	兵营
	DECOY,     //	诱饵
	BRIDGE,     //	桥
	TRANSPORTATION,     //	输送
	GCI,     //	战场侦察雷达
	HQ,     //	总部
	JOINT_HQ,     //	联合总部
	COMMS_NODE,     //	通信结点
	GROUND,     //	地面
	EWR_SITE,     //	远程警戒雷达站
	TRANSPORT_HELICOPTER,     //	运输直升机
	HELOCOPTER,     //	直升机
	HFDF_FACILITY,     //	高频测向设施
	LCAC	,     //气垫登陆艇
	MINE_SWEEPER,     //	扫雷舰
	MISSILE	,     //导弹
	NAVAL_FAC	,     //海军联合咨询委员会
	POL	,     //油料
	PORT,     //港口
	POWER_PLANT	,     //发电站
	RESEARCH,     //	搜索
	RADIO_RELAY	,     //无线通信转播
	SATELLITE,     //	人造卫星
	SIGNAL_SITE,     //	信号站
	TEL	,     //电话
	UAV	,     //无人机
	SPECFORCES,     //	特种部队
	WIRE_RELAY,     //	电报转播
	ARMORED	,     //装甲
	INFANTRY,     //	步兵
	FIELD_ARTILLERY	,     //炮兵战场
	ENGINEER,     //	工兵
	ARMOR_WHEELED,     //	装甲车
	INFANTRY_MECHANIZED	,     //机械化步兵
	INFANTRY_AIRBORNE,     //	空降步兵
	INFANTRY_AIR_ASSAULT,     //	空袭步兵
	GROUND_LAR,     //	地面后勤援助
	GROUND_AAV,     //	地面两栖突击车
	ADA_AVENGER	,     //复仇者防空炮
	ADA	,     //防空炮
	SUPPLY	,     //补给
	TRUCK	,     //货车
	MOUNT_INF	,     //中程核力量装配
	ARMORED_ARTILLERY,     //	装甲炮兵
	CARGO	,     //船货
	ANY	,     //任意
	AIR	,     //空中
	LAND,     //	陆地
	SEA_SURFACE_HOVERCRAFT	,     //水面-气垫船
	SEA_SURFACE_PATROL,     //	水面-巡逻舰
	SEA_SURFACE_PATROL_SUW,     //水面-水面战巡逻舰
	SEA_SURFACE_CRUISER	,     //水面-巡洋舰
	SEA_SURFACE_DESTROYER,     //	水面-驱逐舰
	SEA_SURFACE_FRIGATE	,     //水面-护卫舰
	SEA_SURFACE_AMPHIB,     //	水面-两栖
	SEA_SURFACE_AMPHIB_ASSAULT,     //	水面-两栖-攻击舰
	SEA_SURFACE_AMPHIB_LANDING_SHIP,     //	水面-两栖-登陆舰
	SEA_SURFACE_AMPHIB_LANDING_CRAFT,     //	水面-两栖-登陆艇
	SUBSURFACE_CONVENTIONAL,     //	水下-常规
	SUBSURFACE_NUCLEAR,     //	水下-核
	AIR_FIGHTER,     //	空中-战斗机
	AIR_FIGHTER_INTERCEPTOR,     //	空中-战斗机-拦截机
	AIR_STRIKE,     //	空中-打击
	AIR_VSTOL,     //	空中-垂直短距起落飞机
	AIR_TANKER,     //	空中-加油机
	AIR_JAMMER,     //	空中-干扰发射台
	AIR_RECONNAISSANCE,     //	空中-侦查机
	AIR_RECONNAISSANCE_ESM,     //	空中-侦查_ESM
	AIR_RECONNAISSANCE_PHOTO,     //	空中-侦查-照片
	AIR_PATROL	,     //空中-巡逻机
	AIR_HELOCOPTER_STRIKE,     //	空中-打击直升机
	AIR_HELOCOPTER_PATROL,     //	空中-巡逻直升机
	AIR_HELOCOPTER_UAV,     //	空中-直升机-无人机
	ARTILLERY_TARGET_ACQ,     //	炮-目标ACQ
	ARTILLERY_HOWITZER_LIGHT,     //	炮-榴弹炮-指引
	ARTILLERY_MRL_SP,     //	炮-复杂火箭发射装置-自动助推
	GROUND_RECONNAISSANCE_MARINE_FORCE,     //	地面-侦查舰队兵力
	GROUND_SIGINT_EW_VEHICLE,     //	地面-情报电子战车辆
	GROUND_SIGINT_EW_DF,     //	地面-情报电子战-DF
	GROUND_STATION_MODULE,	//地面站单元
	SMALL_CIRCLE,//	小循环
	DOT	,//运输部
	AEW	,//空中预警
	TRANSPORT_AIRCRAFT_LIGHT,//	运输机指引
	AIRCRAFT	,//飞机
	AIRHOSTILE,//	空中敌方
	ASHORE,//	上岸
	LAND_FAC,//	陆地设施
	SUBSURFACE,//	水下
	SUBHOSTILE	,//水下敌方
	SURFACE	,//水面
	SURFNEUTRL	,//水面中立方
	SURFFRIEND,//	水面友方
	CARRIER	,//航空母舰
	AIRBASE	,//空军基地
	AIRFIELD,//	机场
	SAM_SITE,//	地对空导弹发射装置
	AMMO_DUMP,//	弹药库
	WEAPON_FLYPUT,			//通用小导弹
	SAM,				//对空导弹武器			
	AGW,				//自动制导武器
	AAM,				//空空导弹
	ARM,				//反雷达导弹
	IW_WEAPON,			//信息战武器	
	TORPEDO,				//鱼雷武器
	///////////////////////陆战用军标补充 2016.07
	LAND_OBS_ABATIS1,  //铁丝网1
	LAND_OBS_ABATIS2,  //铁丝网2
	LAND_OBS_JUMA,  //拒马
	LAND_OBS_GUITIAO,  //轨条砦
	LAND_OBS_SANJIAOZHUI,  //三角锥
	LAND_LANDMINE_INFANTRY,  //防步兵雷场
	LAND_AGAIRBASE,  //反机降场
	LAND_GROUND_FORTRESS,  //地堡
	LAND_BLINDAGE_INFANTRY,  //掩体
	LAND_BLINDAGE_TANK,  //坦克掩体
	LAND_LANDMINE_TANK,  //防坦克雷场 
	LAND_WORK_HIDE,  //掩蔽部
	LAND_WORK_ALAWY,  //永备工事
	LAND_LOOKIN_SITE,  //观通站
	LAND_OBSERVE_SITE,  //观察所
	LAND_RADAR_SITE,  //雷达站

	ACKACK_FORCE,  //高炮分队
	COASTGUN_FORCE,  //坦克炮塔分队
	SPECIAL_FORCE,  //两栖队
	DESTROYBARR_FORCE,  //工程分队（爆破）
	AGTANKROCK_FORCE,  //反坦克火箭分队
	AGTANKMISSILE_FORCE,  //反坦克导弹分队
	AERIALDEFEN_FORCE,  //防空分队
	MORTAR_FORCE,  //迫击炮分队
	INFANTRYVEHICLE_FORCE,  //装甲步兵分队
	SHORCKVEHICLE_FORCE,  //突击车分队
	CANIST_FORCE,  //榴炮分队
	INFANTRY_FORCE,  //步兵分队

	GROUND_AIR_MISSILE,  //地空导弹
	BANK_SHIP_MISSILE,  //岸舰导弹
	ARMED_HELOCOPTER,  //武装直升机
	SEA_SURFACE_CWLANDING,  //船坞登陆舰
	SEA_SURFACE_ASSAULT,  //冲锋舟
	SEA_SURFACE_JIAO,  //角反射艇

	LAND_SHOREBEACH_OBS,  //岸滩混合障碍场
	LAND_WATER_OBS,  //水际混合障碍场
	LAND_ROAD,//通路
	LAND_SMOKE,//烟幕
	LAND_FORTIFICATION,//工程分队（筑城）
	LAND_BOATBRIDGE,//工程分队（舟桥）
	LAND_COMM,//通信分队
	LAND_ANTICHEM,//防化分队
	LAND_ANTICHEM_SMOKE,//防化分队（发烟）
	LAND_ENSURE,//保障分队
	LAND_HESCATTERGUN,//重机枪分队
	LAND_TRACTIONARTILLERY,//牵引火炮分队
	LAND_WZLARTILLERY,//无坐力炮分队
	AD_SHOCKFORMATION,//岸导突击群
	CHAFF_PROJECTILE=186, //箔条弹
	MINE_SWEEPER_BOAT,    //	扫雷艇
	MINE, //水雷
	MINE_LAY,//布雷舰
	MINE_HURT,//猎雷舰
	ANY_AIR	,     //任意
	ANY_SURFACE	,     //任意
	ANY_SUBSURFACE	,     //任意
	ANY_LAND,    //任意
	ANY_MISSILE    //任意
};

enum Mars_Identification
{
	ID_None, 
	ID_Unknown,
	ID_HELICOPTER,
	ID_AIRCRAFT_AIRBORNE_C2,
	ID_AIRCRAFT_AIR_LIFT,
	ID_AIRCRAFT_AMCM,
	ID_AIRCRAFT_ATTACK,
	ID_AIRCRAFT_COMMERCIAL,
	ID_AIRCRAFT_EW,
	ID_AIRCRAFT_FIGHTER,
	ID_AIRCRAFT_MPA,
	ID_AIRCRAFT_RECCE,
	ID_AIRCRAFT_SPECOPS,
	ID_AIRCRAFT_STRIKE_FIGHTER,
	ID_AIRCRAFT_TANKER,
	ID_FACILITY,
	ID_FACILITY_AIR_BASE,
	ID_FACILITY_AMMO_DUMP,
	ID_FACILITY_OCEAN_SURVEILLANCE,
	ID_FACILITY_POL,
	ID_FACILITY_POWER_PLANT,
	ID_FACILITY_PRODUCTION,
	ID_FACILITY_RAIL_HEAD,
	ID_FACILITY_SEA_PORT,
	ID_FACILITY_SUPPLY,
	ID_FACILITY_BUILDING,
	ID_FACILITY_BUILDING_COMM_STATION,
	ID_FACILITY_BUILDING_CONTROL_TOWER,
	ID_FACILITY_BUILDING_FUSION_CENTER,
	ID_FACILITY_BUILDING_HQ,
	ID_FACILITY_BUILDING_WAREHOUSE,
	ID_FACILITY_DEFENSIVE_SITE,
	ID_FACILITY_DEFENSIVE_SITE_AAA,
	ID_FACILITY_DEFENSIVE_SITE_COASTAL_ARTY,
	ID_FACILITY_DEFENSIVE_SITE_COASTAL_SSM,
	ID_FACILITY_DEFENSIVE_SITE_EWR,
	ID_FACILITY_DEFENSIVE_SITE_LAND,
	ID_FACILITY_DEFENSIVE_SITE_SAM,
	ID_MINE,
	ID_MISSILE,
	ID_MISSILE_CRUISE_MISSILE,
	ID_MISSILE_TBM,
	ID_SATELLITE,
	ID_SHIP,
	ID_SHIP_AIRCRAFT_CARRIER,
	ID_SHIP_AMPHIBIOUS_ASSAULT,
	ID_SHIP_COASTAL_PATROL,
	ID_SHIP_COMMAND,
	ID_SHIP_CRANE,
	ID_SHIP_HEAVY_LIFT,
	ID_SHIP_HOSPITAL,
	ID_SHIP_LANDING_CRAFT,
	ID_SHIP_MERCHANT,
	ID_SHIP_NAVAL_SURFACE_COMBATANT,
	ID_SHIP_OCEAN_SURVEILLANCE,
	ID_SHIP_REPAIR,
	ID_SHIP_REPLENISHMENT,
	ID_SHIP_SEA_LIFT,
	ID_SHIP_SMCM,
	ID_SHIP_SPECOPS,
	ID_SHIP_SURFACE,
	ID_SHIP_TANKER,
	ID_SUBMARINE,
	ID_SUBMARINE_DIESEL_ELECTRIC,
	ID_SUBMARINE_MINI,
	ID_SUBMARINE_NUCLEAR_POWERED,
	ID_VEHICLE,
	ID_VEHICLE_AAA,
	ID_VEHICLE_AMPHIBIOUS_COMBAT,
	ID_VEHICLE_APC,
	ID_VEHICLE_COMMAND,
	ID_VEHICLE_ENGINEERING,
	ID_VEHICLE_EW,
	ID_VEHICLE_IFV,
	ID_VEHICLE_LIFT,
	ID_VEHICLE_RECCE,
	ID_VEHICLE_REPAIR,
	ID_VEHICLE_ROCKET_LAUNCHER,
	ID_VEHICLE_SAM,
	ID_VEHICLE_SPH,
	ID_VEHICLE_SSM_TEL,
	ID_VEHICLE_TANK,
	ID_VEHICLE_TBM_TEL,
	ID_VEHICLE_TOWED_HOWITZER,
	ID_VEHICLE_TRAILER,
	ID_GROUND_UNIT,
	ID_GROUND_UNIT_ARMOR_BN,
	ID_GROUND_UNIT_MECHANIZED_BN,
	ID_GROUND_UNIT_ARTILLERY_BN,
	ID_GROUND_UNIT_INFANTRY_BN,
	ID_POSSIBLE_SUB,
	ID_SHIP_DESTROYER,
	ID_SHIP_FRIGATE,
	ID_SHIP_CRUISER,
};
enum Mars_Classification
{
	Mars_FRI,//
	Mars_HOS,
	Mars_NEU,
	Mars_UNKNOWN,
	Mars_YOU// add by liang 20151210
};

enum Mars_Alliance{
	M_BLUE=0,
	M_RED,
	M_WHITE,
	M_GREEN,
	M_YELLOW,
	M_ORANGE,
	M_BLACK,
	M_PURPLE,
	M_CYAN,
	M_BROWN,
	M_TOTAL
};

enum Mars_Operating_medium{
	ME_AIR	,//空中
	ME_SURFACE,//水面
	ME_SPACE,//	空间
	ME_LAND,//	陆地
	ME_SUBSURFACE,//	水下
	ME_UNKNOW
};
enum Mars_OpsStatus{
	IN_PORT,//	在港内
	TRANSIT,//	运输
	PATROL,//	巡逻
	UNREP	//航行中补给
};

