# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = SimDataAnalyzer
QT += core gui widgets printsupport
CONFIG += c++17
LIBS += -luser32
QMAKE_CXXFLAGS += -std=c++17
msvc {
    QMAKE_CFLAGS += /utf-8
    QMAKE_CXXFLAGS += /utf-8
    DEFINES += NOMINMAX
}
include(PlotXYDemo.pri)
