/********************************************************************************
** Form generated from reading UI file 'PlotXYDemo.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PLOTXYDEMO_H
#define UI_PLOTXYDEMO_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_PlotXYDemo
{
public:
    QAction *actionopen;
    QAction *actionexport;
    QAction *actionclose;
    QAction *actionLoad_PML;
    QAction *actionSave_to_PML;
    QAction *actionUndo_Ctrl_Z;
    QAction *actionRedo_Ctrl_Y;
    QAction *actionCut_Ctrl_X;
    QAction *actionCopy_Ctrl_C;
    QAction *actionPaste_Ctrl_V;
    QAction *actionDelete;
    QAction *actionSelect_Plot;
    QAction *actionBring_To_Front_Ctrl;
    QAction *actionSend_To_Back_Ctrl;
    QAction *actionBring_Forward;
    QAction *actionSend_Backward;
    QAction *actionTile_Horizontally;
    QAction *actionTile_Vertically;
    QAction *actionSave_Screenshot;
    QAction *actionQuit;
    QAction *action1;
    QAction *action2;
    QAction *action3;
    QAction *action4;
    QAction *action5;
    QAction *action6;
    QAction *action7;
    QAction *action8;
    QAction *action9;
    QAction *action10;
    QAction *actionClear_recent_files;
    QAction *action1_2;
    QAction *action2_2;
    QAction *action3_2;
    QAction *action4_2;
    QAction *action5_2;
    QAction *action6_2;
    QAction *action7_2;
    QAction *action8_2;
    QAction *action9_2;
    QAction *action10_2;
    QAction *actionClear_recent_files_2;
    QAction *actionPlot_Wizard;
    QAction *actionPlot_Manager_Ctrl_M;
    QAction *actionWidget_Editor;
    QAction *actionExport_to_GOG;
    QAction *actionCreate_Plot;
    QAction *actionAutofit;
    QAction *actionOne_To_One;
    QAction *actionRound_Ranges;
    QAction *actionLock_Data_Display;
    QAction *actionLock_Stacking_Order;
    QAction *actionInvert_Colores;
    QAction *actionAdvanced_Data_Manager;
    QAction *actionAdd_Plot_Pair_Ctrl_A;
    QAction *actionDiscovery_Rules;
    QAction *actionShow_Object_Aliases_Ctrl_Alt_A;
    QAction *actionReference_Points_Ctrl_R;
    QAction *actionEntity_Status_Ctrl_Alt_S;
    QAction *actionClassification;
    QAction *actionPlay;
    QAction *actionReverse;
    QAction *actionReal_Time;
    QAction *actionTime_Controls;
    QAction *actionTime_Client;
    QAction *actionTime_Server;
    QAction *actionNew_Tab_Ctrl_T;
    QAction *actionRename_Tab;
    QAction *actionClose_Tab;
    QAction *actionNext_Tab_Ctrl_Tab;
    QAction *actionPrevious_Tab_Ctrl_Shift_Tab;
    QAction *actionShow_Menubar_Ctrl_Alt_M;
    QAction *actionShow_Toolbar_Ctrl_Alt_C;
    QAction *actionShow_Statusbar_Ctrl_Alt_B;
    QAction *actionShow_Time_Slider;
    QAction *actionShow_Tabbar;
    QAction *actionShow_RTI_Controls;
    QAction *actionShow_All_Bars_Ctrl_B;
    QAction *actionShow_Plot_Time_Ctrl_Alt_P;
    QAction *actionShow_System_Time_Ctrl_Alt_Y;
    QAction *actionShow_Corner_Logo;
    QAction *actionShow_Frame_Rate_Alt_F;
    QAction *actionFullScreen_Shift_F;
    QAction *actionSave_Preferences;
    QAction *actionSave_Preferences_As;
    QAction *actionLoad_Preferences;
    QAction *actionUseer_Functions;
    QAction *actionFunction_Console;
    QAction *actionHot_Keys_Ctrl_H;
    QAction *actionOptions_Ctrl_Alt_O;
    QAction *actionPlug_in_Manager;
    QAction *actionConsole_Ctrl_F1;
    QAction *actionFind_DCS_Sever;
    QAction *actionHDF5_Export;
    QAction *actionHDF5_Import;
    QAction *actionSimple_Sever;
    QAction *actionSp_Batch_Loader;
    QAction *actionsimVideo_Recorder;
    QAction *actionUser_Manual_F1;
    QAction *actionTraining;
    QAction *actionAbout;
    QAction *actionSave_Snapshot;
    QAction *actionRun_Python_Script_Ctrl_E;
    QAction *actionDecrease_Step;
    QAction *actionFrame_Rverse;
    QAction *actionStop;
    QAction *actionFrame_Forward;
    QAction *actionIncrease_Step;
    QAction *actionselect_plot;
    QWidget *centralWidget;
    QVBoxLayout *verticalLayout;
    QTabWidget *tabWidget;
    QWidget *tab;
    QWidget *tab_2;
    QWidget *tab_3;
    QMenuBar *menuBar;
    QMenu *menufile;
    QMenu *menuRecent_Files;
    QMenu *menuRecent_PMLs;
    QMenu *menuEdit;
    QMenu *menuOrder;
    QMenu *menuGraph;
    QMenu *menuData;
    QMenu *menuTime;
    QMenu *menuTabs;
    QMenu *menuView;
    QMenu *menuTools;
    QMenu *menuBookmarks;
    QMenu *menuPlug_ins;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *PlotXYDemo)
    {
        if (PlotXYDemo->objectName().isEmpty())
            PlotXYDemo->setObjectName(QStringLiteral("PlotXYDemo"));
        PlotXYDemo->resize(1079, 584);
        PlotXYDemo->setStyleSheet(QStringLiteral("alternate-background-color: rgb(0, 85, 127);"));
        actionopen = new QAction(PlotXYDemo);
        actionopen->setObjectName(QStringLiteral("actionopen"));
        QIcon icon;
        icon.addFile(QStringLiteral(":/toolbar/openfile.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionopen->setIcon(icon);
        actionexport = new QAction(PlotXYDemo);
        actionexport->setObjectName(QStringLiteral("actionexport"));
        actionclose = new QAction(PlotXYDemo);
        actionclose->setObjectName(QStringLiteral("actionclose"));
        actionLoad_PML = new QAction(PlotXYDemo);
        actionLoad_PML->setObjectName(QStringLiteral("actionLoad_PML"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/res/openfile.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon1.addFile(QStringLiteral(":/toolbar/loadpml.png"), QSize(), QIcon::Normal, QIcon::On);
        actionLoad_PML->setIcon(icon1);
        actionSave_to_PML = new QAction(PlotXYDemo);
        actionSave_to_PML->setObjectName(QStringLiteral("actionSave_to_PML"));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/res/openfile.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon2.addFile(QStringLiteral(":/toolbar/savepml.png"), QSize(), QIcon::Normal, QIcon::On);
        actionSave_to_PML->setIcon(icon2);
        actionUndo_Ctrl_Z = new QAction(PlotXYDemo);
        actionUndo_Ctrl_Z->setObjectName(QStringLiteral("actionUndo_Ctrl_Z"));
        actionRedo_Ctrl_Y = new QAction(PlotXYDemo);
        actionRedo_Ctrl_Y->setObjectName(QStringLiteral("actionRedo_Ctrl_Y"));
        actionCut_Ctrl_X = new QAction(PlotXYDemo);
        actionCut_Ctrl_X->setObjectName(QStringLiteral("actionCut_Ctrl_X"));
        actionCopy_Ctrl_C = new QAction(PlotXYDemo);
        actionCopy_Ctrl_C->setObjectName(QStringLiteral("actionCopy_Ctrl_C"));
        actionPaste_Ctrl_V = new QAction(PlotXYDemo);
        actionPaste_Ctrl_V->setObjectName(QStringLiteral("actionPaste_Ctrl_V"));
        actionDelete = new QAction(PlotXYDemo);
        actionDelete->setObjectName(QStringLiteral("actionDelete"));
        actionSelect_Plot = new QAction(PlotXYDemo);
        actionSelect_Plot->setObjectName(QStringLiteral("actionSelect_Plot"));
        actionBring_To_Front_Ctrl = new QAction(PlotXYDemo);
        actionBring_To_Front_Ctrl->setObjectName(QStringLiteral("actionBring_To_Front_Ctrl"));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/toolbar/Takefront.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionBring_To_Front_Ctrl->setIcon(icon3);
        actionSend_To_Back_Ctrl = new QAction(PlotXYDemo);
        actionSend_To_Back_Ctrl->setObjectName(QStringLiteral("actionSend_To_Back_Ctrl"));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/toolbar/Takeback.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSend_To_Back_Ctrl->setIcon(icon4);
        actionBring_Forward = new QAction(PlotXYDemo);
        actionBring_Forward->setObjectName(QStringLiteral("actionBring_Forward"));
        actionSend_Backward = new QAction(PlotXYDemo);
        actionSend_Backward->setObjectName(QStringLiteral("actionSend_Backward"));
        actionTile_Horizontally = new QAction(PlotXYDemo);
        actionTile_Horizontally->setObjectName(QStringLiteral("actionTile_Horizontally"));
        actionTile_Vertically = new QAction(PlotXYDemo);
        actionTile_Vertically->setObjectName(QStringLiteral("actionTile_Vertically"));
        actionSave_Screenshot = new QAction(PlotXYDemo);
        actionSave_Screenshot->setObjectName(QStringLiteral("actionSave_Screenshot"));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/toolbar/snapshot.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_Screenshot->setIcon(icon5);
        actionQuit = new QAction(PlotXYDemo);
        actionQuit->setObjectName(QStringLiteral("actionQuit"));
        action1 = new QAction(PlotXYDemo);
        action1->setObjectName(QStringLiteral("action1"));
        action2 = new QAction(PlotXYDemo);
        action2->setObjectName(QStringLiteral("action2"));
        action3 = new QAction(PlotXYDemo);
        action3->setObjectName(QStringLiteral("action3"));
        action4 = new QAction(PlotXYDemo);
        action4->setObjectName(QStringLiteral("action4"));
        action5 = new QAction(PlotXYDemo);
        action5->setObjectName(QStringLiteral("action5"));
        action6 = new QAction(PlotXYDemo);
        action6->setObjectName(QStringLiteral("action6"));
        action7 = new QAction(PlotXYDemo);
        action7->setObjectName(QStringLiteral("action7"));
        action8 = new QAction(PlotXYDemo);
        action8->setObjectName(QStringLiteral("action8"));
        action9 = new QAction(PlotXYDemo);
        action9->setObjectName(QStringLiteral("action9"));
        action10 = new QAction(PlotXYDemo);
        action10->setObjectName(QStringLiteral("action10"));
        actionClear_recent_files = new QAction(PlotXYDemo);
        actionClear_recent_files->setObjectName(QStringLiteral("actionClear_recent_files"));
        action1_2 = new QAction(PlotXYDemo);
        action1_2->setObjectName(QStringLiteral("action1_2"));
        action2_2 = new QAction(PlotXYDemo);
        action2_2->setObjectName(QStringLiteral("action2_2"));
        action3_2 = new QAction(PlotXYDemo);
        action3_2->setObjectName(QStringLiteral("action3_2"));
        action4_2 = new QAction(PlotXYDemo);
        action4_2->setObjectName(QStringLiteral("action4_2"));
        action5_2 = new QAction(PlotXYDemo);
        action5_2->setObjectName(QStringLiteral("action5_2"));
        action6_2 = new QAction(PlotXYDemo);
        action6_2->setObjectName(QStringLiteral("action6_2"));
        action7_2 = new QAction(PlotXYDemo);
        action7_2->setObjectName(QStringLiteral("action7_2"));
        action8_2 = new QAction(PlotXYDemo);
        action8_2->setObjectName(QStringLiteral("action8_2"));
        action9_2 = new QAction(PlotXYDemo);
        action9_2->setObjectName(QStringLiteral("action9_2"));
        action10_2 = new QAction(PlotXYDemo);
        action10_2->setObjectName(QStringLiteral("action10_2"));
        actionClear_recent_files_2 = new QAction(PlotXYDemo);
        actionClear_recent_files_2->setObjectName(QStringLiteral("actionClear_recent_files_2"));
        actionPlot_Wizard = new QAction(PlotXYDemo);
        actionPlot_Wizard->setObjectName(QStringLiteral("actionPlot_Wizard"));
        actionPlot_Manager_Ctrl_M = new QAction(PlotXYDemo);
        actionPlot_Manager_Ctrl_M->setObjectName(QStringLiteral("actionPlot_Manager_Ctrl_M"));
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/toolbar/plotmanager.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPlot_Manager_Ctrl_M->setIcon(icon6);
        actionWidget_Editor = new QAction(PlotXYDemo);
        actionWidget_Editor->setObjectName(QStringLiteral("actionWidget_Editor"));
        actionExport_to_GOG = new QAction(PlotXYDemo);
        actionExport_to_GOG->setObjectName(QStringLiteral("actionExport_to_GOG"));
        actionCreate_Plot = new QAction(PlotXYDemo);
        actionCreate_Plot->setObjectName(QStringLiteral("actionCreate_Plot"));
        actionAutofit = new QAction(PlotXYDemo);
        actionAutofit->setObjectName(QStringLiteral("actionAutofit"));
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/toolbar/autoadjust.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionAutofit->setIcon(icon7);
        actionOne_To_One = new QAction(PlotXYDemo);
        actionOne_To_One->setObjectName(QStringLiteral("actionOne_To_One"));
        actionRound_Ranges = new QAction(PlotXYDemo);
        actionRound_Ranges->setObjectName(QStringLiteral("actionRound_Ranges"));
        actionLock_Data_Display = new QAction(PlotXYDemo);
        actionLock_Data_Display->setObjectName(QStringLiteral("actionLock_Data_Display"));
        actionLock_Stacking_Order = new QAction(PlotXYDemo);
        actionLock_Stacking_Order->setObjectName(QStringLiteral("actionLock_Stacking_Order"));
        actionInvert_Colores = new QAction(PlotXYDemo);
        actionInvert_Colores->setObjectName(QStringLiteral("actionInvert_Colores"));
        actionAdvanced_Data_Manager = new QAction(PlotXYDemo);
        actionAdvanced_Data_Manager->setObjectName(QStringLiteral("actionAdvanced_Data_Manager"));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/toolbar/AdvancedDataManager.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionAdvanced_Data_Manager->setIcon(icon8);
        actionAdd_Plot_Pair_Ctrl_A = new QAction(PlotXYDemo);
        actionAdd_Plot_Pair_Ctrl_A->setObjectName(QStringLiteral("actionAdd_Plot_Pair_Ctrl_A"));
        QIcon icon9;
        icon9.addFile(QStringLiteral(":/toolbar/AddPlotPair.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionAdd_Plot_Pair_Ctrl_A->setIcon(icon9);
        actionDiscovery_Rules = new QAction(PlotXYDemo);
        actionDiscovery_Rules->setObjectName(QStringLiteral("actionDiscovery_Rules"));
        actionShow_Object_Aliases_Ctrl_Alt_A = new QAction(PlotXYDemo);
        actionShow_Object_Aliases_Ctrl_Alt_A->setObjectName(QStringLiteral("actionShow_Object_Aliases_Ctrl_Alt_A"));
        actionShow_Object_Aliases_Ctrl_Alt_A->setCheckable(true);
        actionReference_Points_Ctrl_R = new QAction(PlotXYDemo);
        actionReference_Points_Ctrl_R->setObjectName(QStringLiteral("actionReference_Points_Ctrl_R"));
        actionEntity_Status_Ctrl_Alt_S = new QAction(PlotXYDemo);
        actionEntity_Status_Ctrl_Alt_S->setObjectName(QStringLiteral("actionEntity_Status_Ctrl_Alt_S"));
        actionClassification = new QAction(PlotXYDemo);
        actionClassification->setObjectName(QStringLiteral("actionClassification"));
        actionPlay = new QAction(PlotXYDemo);
        actionPlay->setObjectName(QStringLiteral("actionPlay"));
        QIcon icon10;
        icon10.addFile(QStringLiteral(":/toolbar/Play.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPlay->setIcon(icon10);
        actionReverse = new QAction(PlotXYDemo);
        actionReverse->setObjectName(QStringLiteral("actionReverse"));
        QIcon icon11;
        icon11.addFile(QStringLiteral(":/toolbar/PlayBack.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionReverse->setIcon(icon11);
        actionReal_Time = new QAction(PlotXYDemo);
        actionReal_Time->setObjectName(QStringLiteral("actionReal_Time"));
        QIcon icon12;
        icon12.addFile(QStringLiteral(":/toolbar/RealTime.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionReal_Time->setIcon(icon12);
        actionTime_Controls = new QAction(PlotXYDemo);
        actionTime_Controls->setObjectName(QStringLiteral("actionTime_Controls"));
        QIcon icon13;
        icon13.addFile(QStringLiteral(":/toolbar/TimeEditor.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionTime_Controls->setIcon(icon13);
        actionTime_Client = new QAction(PlotXYDemo);
        actionTime_Client->setObjectName(QStringLiteral("actionTime_Client"));
        QIcon icon14;
        icon14.addFile(QStringLiteral(":/toolbar/TimeClient.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionTime_Client->setIcon(icon14);
        actionTime_Server = new QAction(PlotXYDemo);
        actionTime_Server->setObjectName(QStringLiteral("actionTime_Server"));
        QIcon icon15;
        icon15.addFile(QStringLiteral(":/toolbar/TimeServer.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionTime_Server->setIcon(icon15);
        actionNew_Tab_Ctrl_T = new QAction(PlotXYDemo);
        actionNew_Tab_Ctrl_T->setObjectName(QStringLiteral("actionNew_Tab_Ctrl_T"));
        actionRename_Tab = new QAction(PlotXYDemo);
        actionRename_Tab->setObjectName(QStringLiteral("actionRename_Tab"));
        actionClose_Tab = new QAction(PlotXYDemo);
        actionClose_Tab->setObjectName(QStringLiteral("actionClose_Tab"));
        actionNext_Tab_Ctrl_Tab = new QAction(PlotXYDemo);
        actionNext_Tab_Ctrl_Tab->setObjectName(QStringLiteral("actionNext_Tab_Ctrl_Tab"));
        actionPrevious_Tab_Ctrl_Shift_Tab = new QAction(PlotXYDemo);
        actionPrevious_Tab_Ctrl_Shift_Tab->setObjectName(QStringLiteral("actionPrevious_Tab_Ctrl_Shift_Tab"));
        actionShow_Menubar_Ctrl_Alt_M = new QAction(PlotXYDemo);
        actionShow_Menubar_Ctrl_Alt_M->setObjectName(QStringLiteral("actionShow_Menubar_Ctrl_Alt_M"));
        actionShow_Menubar_Ctrl_Alt_M->setCheckable(true);
        actionShow_Menubar_Ctrl_Alt_M->setChecked(false);
        actionShow_Toolbar_Ctrl_Alt_C = new QAction(PlotXYDemo);
        actionShow_Toolbar_Ctrl_Alt_C->setObjectName(QStringLiteral("actionShow_Toolbar_Ctrl_Alt_C"));
        actionShow_Toolbar_Ctrl_Alt_C->setCheckable(true);
        actionShow_Toolbar_Ctrl_Alt_C->setChecked(false);
        actionShow_Statusbar_Ctrl_Alt_B = new QAction(PlotXYDemo);
        actionShow_Statusbar_Ctrl_Alt_B->setObjectName(QStringLiteral("actionShow_Statusbar_Ctrl_Alt_B"));
        actionShow_Statusbar_Ctrl_Alt_B->setCheckable(true);
        actionShow_Time_Slider = new QAction(PlotXYDemo);
        actionShow_Time_Slider->setObjectName(QStringLiteral("actionShow_Time_Slider"));
        actionShow_Time_Slider->setCheckable(true);
        actionShow_Tabbar = new QAction(PlotXYDemo);
        actionShow_Tabbar->setObjectName(QStringLiteral("actionShow_Tabbar"));
        actionShow_Tabbar->setCheckable(true);
        actionShow_RTI_Controls = new QAction(PlotXYDemo);
        actionShow_RTI_Controls->setObjectName(QStringLiteral("actionShow_RTI_Controls"));
        actionShow_RTI_Controls->setCheckable(true);
        actionShow_All_Bars_Ctrl_B = new QAction(PlotXYDemo);
        actionShow_All_Bars_Ctrl_B->setObjectName(QStringLiteral("actionShow_All_Bars_Ctrl_B"));
        actionShow_Plot_Time_Ctrl_Alt_P = new QAction(PlotXYDemo);
        actionShow_Plot_Time_Ctrl_Alt_P->setObjectName(QStringLiteral("actionShow_Plot_Time_Ctrl_Alt_P"));
        actionShow_System_Time_Ctrl_Alt_Y = new QAction(PlotXYDemo);
        actionShow_System_Time_Ctrl_Alt_Y->setObjectName(QStringLiteral("actionShow_System_Time_Ctrl_Alt_Y"));
        actionShow_Corner_Logo = new QAction(PlotXYDemo);
        actionShow_Corner_Logo->setObjectName(QStringLiteral("actionShow_Corner_Logo"));
        actionShow_Frame_Rate_Alt_F = new QAction(PlotXYDemo);
        actionShow_Frame_Rate_Alt_F->setObjectName(QStringLiteral("actionShow_Frame_Rate_Alt_F"));
        actionFullScreen_Shift_F = new QAction(PlotXYDemo);
        actionFullScreen_Shift_F->setObjectName(QStringLiteral("actionFullScreen_Shift_F"));
        actionSave_Preferences = new QAction(PlotXYDemo);
        actionSave_Preferences->setObjectName(QStringLiteral("actionSave_Preferences"));
        actionSave_Preferences_As = new QAction(PlotXYDemo);
        actionSave_Preferences_As->setObjectName(QStringLiteral("actionSave_Preferences_As"));
        actionLoad_Preferences = new QAction(PlotXYDemo);
        actionLoad_Preferences->setObjectName(QStringLiteral("actionLoad_Preferences"));
        actionUseer_Functions = new QAction(PlotXYDemo);
        actionUseer_Functions->setObjectName(QStringLiteral("actionUseer_Functions"));
        actionFunction_Console = new QAction(PlotXYDemo);
        actionFunction_Console->setObjectName(QStringLiteral("actionFunction_Console"));
        actionHot_Keys_Ctrl_H = new QAction(PlotXYDemo);
        actionHot_Keys_Ctrl_H->setObjectName(QStringLiteral("actionHot_Keys_Ctrl_H"));
        actionOptions_Ctrl_Alt_O = new QAction(PlotXYDemo);
        actionOptions_Ctrl_Alt_O->setObjectName(QStringLiteral("actionOptions_Ctrl_Alt_O"));
        actionPlug_in_Manager = new QAction(PlotXYDemo);
        actionPlug_in_Manager->setObjectName(QStringLiteral("actionPlug_in_Manager"));
        actionConsole_Ctrl_F1 = new QAction(PlotXYDemo);
        actionConsole_Ctrl_F1->setObjectName(QStringLiteral("actionConsole_Ctrl_F1"));
        actionFind_DCS_Sever = new QAction(PlotXYDemo);
        actionFind_DCS_Sever->setObjectName(QStringLiteral("actionFind_DCS_Sever"));
        actionHDF5_Export = new QAction(PlotXYDemo);
        actionHDF5_Export->setObjectName(QStringLiteral("actionHDF5_Export"));
        actionHDF5_Import = new QAction(PlotXYDemo);
        actionHDF5_Import->setObjectName(QStringLiteral("actionHDF5_Import"));
        actionSimple_Sever = new QAction(PlotXYDemo);
        actionSimple_Sever->setObjectName(QStringLiteral("actionSimple_Sever"));
        actionSp_Batch_Loader = new QAction(PlotXYDemo);
        actionSp_Batch_Loader->setObjectName(QStringLiteral("actionSp_Batch_Loader"));
        actionsimVideo_Recorder = new QAction(PlotXYDemo);
        actionsimVideo_Recorder->setObjectName(QStringLiteral("actionsimVideo_Recorder"));
        actionUser_Manual_F1 = new QAction(PlotXYDemo);
        actionUser_Manual_F1->setObjectName(QStringLiteral("actionUser_Manual_F1"));
        actionTraining = new QAction(PlotXYDemo);
        actionTraining->setObjectName(QStringLiteral("actionTraining"));
        actionAbout = new QAction(PlotXYDemo);
        actionAbout->setObjectName(QStringLiteral("actionAbout"));
        actionSave_Snapshot = new QAction(PlotXYDemo);
        actionSave_Snapshot->setObjectName(QStringLiteral("actionSave_Snapshot"));
        actionSave_Snapshot->setIcon(icon5);
        actionRun_Python_Script_Ctrl_E = new QAction(PlotXYDemo);
        actionRun_Python_Script_Ctrl_E->setObjectName(QStringLiteral("actionRun_Python_Script_Ctrl_E"));
        actionDecrease_Step = new QAction(PlotXYDemo);
        actionDecrease_Step->setObjectName(QStringLiteral("actionDecrease_Step"));
        QIcon icon16;
        icon16.addFile(QStringLiteral(":/toolbar/DecTimeStep.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDecrease_Step->setIcon(icon16);
        actionFrame_Rverse = new QAction(PlotXYDemo);
        actionFrame_Rverse->setObjectName(QStringLiteral("actionFrame_Rverse"));
        QIcon icon17;
        icon17.addFile(QStringLiteral(":/toolbar/BackOneStep.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFrame_Rverse->setIcon(icon17);
        actionStop = new QAction(PlotXYDemo);
        actionStop->setObjectName(QStringLiteral("actionStop"));
        QIcon icon18;
        icon18.addFile(QStringLiteral(":/toolbar/Stop.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionStop->setIcon(icon18);
        actionFrame_Forward = new QAction(PlotXYDemo);
        actionFrame_Forward->setObjectName(QStringLiteral("actionFrame_Forward"));
        QIcon icon19;
        icon19.addFile(QStringLiteral(":/toolbar/GoOneStep.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFrame_Forward->setIcon(icon19);
        actionIncrease_Step = new QAction(PlotXYDemo);
        actionIncrease_Step->setObjectName(QStringLiteral("actionIncrease_Step"));
        QIcon icon20;
        icon20.addFile(QStringLiteral(":/toolbar/AddTimeStep.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionIncrease_Step->setIcon(icon20);
        actionselect_plot = new QAction(PlotXYDemo);
        actionselect_plot->setObjectName(QStringLiteral("actionselect_plot"));
        centralWidget = new QWidget(PlotXYDemo);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        verticalLayout = new QVBoxLayout(centralWidget);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        tabWidget->addTab(tab_3, QString());

        verticalLayout->addWidget(tabWidget);

        PlotXYDemo->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(PlotXYDemo);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1079, 22));
        menufile = new QMenu(menuBar);
        menufile->setObjectName(QStringLiteral("menufile"));
        menuRecent_Files = new QMenu(menufile);
        menuRecent_Files->setObjectName(QStringLiteral("menuRecent_Files"));
        menuRecent_PMLs = new QMenu(menufile);
        menuRecent_PMLs->setObjectName(QStringLiteral("menuRecent_PMLs"));
        menuEdit = new QMenu(menuBar);
        menuEdit->setObjectName(QStringLiteral("menuEdit"));
        menuOrder = new QMenu(menuEdit);
        menuOrder->setObjectName(QStringLiteral("menuOrder"));
        menuGraph = new QMenu(menuBar);
        menuGraph->setObjectName(QStringLiteral("menuGraph"));
        menuData = new QMenu(menuBar);
        menuData->setObjectName(QStringLiteral("menuData"));
        menuTime = new QMenu(menuBar);
        menuTime->setObjectName(QStringLiteral("menuTime"));
        menuTabs = new QMenu(menuBar);
        menuTabs->setObjectName(QStringLiteral("menuTabs"));
        menuView = new QMenu(menuBar);
        menuView->setObjectName(QStringLiteral("menuView"));
        menuTools = new QMenu(menuBar);
        menuTools->setObjectName(QStringLiteral("menuTools"));
        menuBookmarks = new QMenu(menuBar);
        menuBookmarks->setObjectName(QStringLiteral("menuBookmarks"));
        menuPlug_ins = new QMenu(menuBar);
        menuPlug_ins->setObjectName(QStringLiteral("menuPlug_ins"));
        PlotXYDemo->setMenuBar(menuBar);
        mainToolBar = new QToolBar(PlotXYDemo);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        PlotXYDemo->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(PlotXYDemo);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        PlotXYDemo->setStatusBar(statusBar);

        menuBar->addAction(menufile->menuAction());
        menuBar->addAction(menuEdit->menuAction());
        menuBar->addAction(menuGraph->menuAction());
        menuBar->addAction(menuData->menuAction());
        menuBar->addAction(menuTime->menuAction());
        menuBar->addAction(menuTabs->menuAction());
        menuBar->addAction(menuView->menuAction());
        menuBar->addAction(menuTools->menuAction());
        menuBar->addAction(menuPlug_ins->menuAction());
        menuBar->addAction(menuBookmarks->menuAction());
        menufile->addAction(actionopen);
        menufile->addAction(actionexport);
        menufile->addSeparator();
        menufile->addAction(actionclose);
        menufile->addSeparator();
        menufile->addAction(actionRun_Python_Script_Ctrl_E);
        menufile->addSeparator();
        menufile->addAction(actionLoad_PML);
        menufile->addAction(actionSave_to_PML);
        menufile->addAction(actionSave_Screenshot);
        menufile->addSeparator();
        menufile->addAction(menuRecent_Files->menuAction());
        menufile->addAction(menuRecent_PMLs->menuAction());
        menufile->addSeparator();
        menufile->addAction(actionQuit);
        menufile->addAction(actionselect_plot);
        menuRecent_Files->addAction(action1);
        menuRecent_Files->addAction(action2);
        menuRecent_Files->addAction(action3);
        menuRecent_Files->addAction(action4);
        menuRecent_Files->addAction(action5);
        menuRecent_Files->addAction(action6);
        menuRecent_Files->addAction(action7);
        menuRecent_Files->addAction(action8);
        menuRecent_Files->addAction(action9);
        menuRecent_Files->addAction(action10);
        menuRecent_Files->addAction(actionClear_recent_files);
        menuRecent_PMLs->addAction(action1_2);
        menuRecent_PMLs->addAction(action2_2);
        menuRecent_PMLs->addAction(action3_2);
        menuRecent_PMLs->addAction(action4_2);
        menuRecent_PMLs->addAction(action5_2);
        menuRecent_PMLs->addAction(action6_2);
        menuRecent_PMLs->addAction(action7_2);
        menuRecent_PMLs->addAction(action8_2);
        menuRecent_PMLs->addAction(action9_2);
        menuRecent_PMLs->addAction(action10_2);
        menuRecent_PMLs->addAction(actionClear_recent_files_2);
        menuEdit->addAction(actionUndo_Ctrl_Z);
        menuEdit->addAction(actionRedo_Ctrl_Y);
        menuEdit->addAction(actionCut_Ctrl_X);
        menuEdit->addAction(actionCopy_Ctrl_C);
        menuEdit->addAction(actionPaste_Ctrl_V);
        menuEdit->addAction(actionDelete);
        menuEdit->addAction(actionSelect_Plot);
        menuEdit->addAction(menuOrder->menuAction());
        menuOrder->addAction(actionBring_To_Front_Ctrl);
        menuOrder->addAction(actionSend_To_Back_Ctrl);
        menuOrder->addAction(actionBring_Forward);
        menuOrder->addAction(actionSend_Backward);
        menuOrder->addSeparator();
        menuOrder->addAction(actionTile_Horizontally);
        menuOrder->addAction(actionTile_Vertically);
        menuGraph->addAction(actionPlot_Wizard);
        menuGraph->addSeparator();
        menuGraph->addAction(actionPlot_Manager_Ctrl_M);
        menuGraph->addAction(actionWidget_Editor);
        menuGraph->addAction(actionExport_to_GOG);
        menuGraph->addSeparator();
        menuGraph->addAction(actionCreate_Plot);
        menuGraph->addSeparator();
        menuGraph->addAction(actionAutofit);
        menuGraph->addAction(actionOne_To_One);
        menuGraph->addAction(actionRound_Ranges);
        menuGraph->addSeparator();
        menuGraph->addAction(actionLock_Data_Display);
        menuGraph->addAction(actionLock_Stacking_Order);
        menuGraph->addSeparator();
        menuGraph->addAction(actionInvert_Colores);
        menuData->addAction(actionAdvanced_Data_Manager);
        menuData->addAction(actionAdd_Plot_Pair_Ctrl_A);
        menuData->addAction(actionDiscovery_Rules);
        menuData->addSeparator();
        menuData->addAction(actionShow_Object_Aliases_Ctrl_Alt_A);
        menuData->addSeparator();
        menuData->addAction(actionReference_Points_Ctrl_R);
        menuData->addAction(actionEntity_Status_Ctrl_Alt_S);
        menuData->addAction(actionClassification);
        menuTime->addAction(actionPlay);
        menuTime->addAction(actionReverse);
        menuTime->addAction(actionReal_Time);
        menuTime->addAction(actionTime_Controls);
        menuTime->addAction(actionTime_Client);
        menuTime->addAction(actionTime_Server);
        menuTabs->addAction(actionNew_Tab_Ctrl_T);
        menuTabs->addAction(actionRename_Tab);
        menuTabs->addAction(actionClose_Tab);
        menuTabs->addAction(actionNext_Tab_Ctrl_Tab);
        menuTabs->addAction(actionPrevious_Tab_Ctrl_Shift_Tab);
        menuView->addAction(actionShow_Menubar_Ctrl_Alt_M);
        menuView->addAction(actionShow_Toolbar_Ctrl_Alt_C);
        menuView->addAction(actionShow_Statusbar_Ctrl_Alt_B);
        menuView->addAction(actionShow_Time_Slider);
        menuView->addAction(actionShow_Tabbar);
        menuView->addAction(actionShow_RTI_Controls);
        menuView->addAction(actionShow_All_Bars_Ctrl_B);
        menuView->addAction(actionShow_Plot_Time_Ctrl_Alt_P);
        menuView->addAction(actionShow_System_Time_Ctrl_Alt_Y);
        menuView->addAction(actionShow_Corner_Logo);
        menuView->addAction(actionShow_Frame_Rate_Alt_F);
        menuView->addAction(actionFullScreen_Shift_F);
        menuTools->addAction(actionSave_Preferences);
        menuTools->addAction(actionSave_Preferences_As);
        menuTools->addAction(actionLoad_Preferences);
        menuTools->addAction(actionUseer_Functions);
        menuTools->addAction(actionFunction_Console);
        menuTools->addAction(actionHot_Keys_Ctrl_H);
        menuTools->addAction(actionOptions_Ctrl_Alt_O);
        menuBookmarks->addAction(actionUser_Manual_F1);
        menuBookmarks->addAction(actionTraining);
        menuBookmarks->addAction(actionAbout);
        menuPlug_ins->addAction(actionPlug_in_Manager);
        menuPlug_ins->addAction(actionConsole_Ctrl_F1);
        menuPlug_ins->addAction(actionFind_DCS_Sever);
        menuPlug_ins->addAction(actionHDF5_Export);
        menuPlug_ins->addAction(actionHDF5_Import);
        menuPlug_ins->addAction(actionSimple_Sever);
        menuPlug_ins->addAction(actionSp_Batch_Loader);
        menuPlug_ins->addAction(actionsimVideo_Recorder);
        mainToolBar->addAction(actionopen);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionLoad_PML);
        mainToolBar->addAction(actionSave_to_PML);
        mainToolBar->addAction(actionPlot_Manager_Ctrl_M);
        mainToolBar->addAction(actionAdvanced_Data_Manager);
        mainToolBar->addAction(actionAdd_Plot_Pair_Ctrl_A);
        mainToolBar->addAction(actionAutofit);
        mainToolBar->addAction(actionBring_To_Front_Ctrl);
        mainToolBar->addAction(actionSend_To_Back_Ctrl);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionSave_Screenshot);
        mainToolBar->addAction(actionTime_Server);
        mainToolBar->addAction(actionTime_Client);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionDecrease_Step);
        mainToolBar->addAction(actionFrame_Rverse);
        mainToolBar->addAction(actionReverse);
        mainToolBar->addAction(actionStop);
        mainToolBar->addAction(actionPlay);
        mainToolBar->addAction(actionFrame_Forward);
        mainToolBar->addAction(actionIncrease_Step);
        mainToolBar->addAction(actionReal_Time);
        mainToolBar->addAction(actionTime_Controls);

        retranslateUi(PlotXYDemo);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(PlotXYDemo);
    } // setupUi

    void retranslateUi(QMainWindow *PlotXYDemo)
    {
        PlotXYDemo->setWindowTitle(QString());
        actionopen->setText(QApplication::translate("PlotXYDemo", "\346\211\223\345\274\200", Q_NULLPTR));
        actionexport->setText(QApplication::translate("PlotXYDemo", "\345\257\274\345\207\272\346\225\260\346\215\256", Q_NULLPTR));
        actionclose->setText(QApplication::translate("PlotXYDemo", "\346\270\205\347\220\206\346\225\260\346\215\256", Q_NULLPTR));
        actionLoad_PML->setText(QApplication::translate("PlotXYDemo", "\345\212\240\350\275\275PML", Q_NULLPTR));
        actionSave_to_PML->setText(QApplication::translate("PlotXYDemo", "\344\277\235\345\255\230PML", Q_NULLPTR));
        actionUndo_Ctrl_Z->setText(QApplication::translate("PlotXYDemo", "\346\222\244\351\224\200  Ctrl+Z", Q_NULLPTR));
        actionRedo_Ctrl_Y->setText(QApplication::translate("PlotXYDemo", "\346\201\242\345\244\215  Ctrl+Y", Q_NULLPTR));
        actionCut_Ctrl_X->setText(QApplication::translate("PlotXYDemo", "\345\211\252\345\210\207  Ctrl+X", Q_NULLPTR));
        actionCopy_Ctrl_C->setText(QApplication::translate("PlotXYDemo", "\345\244\215\345\210\266  Ctrl+C", Q_NULLPTR));
        actionPaste_Ctrl_V->setText(QApplication::translate("PlotXYDemo", "\347\262\230\350\264\264  Ctrl+V", Q_NULLPTR));
        actionDelete->setText(QApplication::translate("PlotXYDemo", "\345\210\240\351\231\244...", Q_NULLPTR));
        actionSelect_Plot->setText(QApplication::translate("PlotXYDemo", "Select Plot", Q_NULLPTR));
        actionBring_To_Front_Ctrl->setText(QApplication::translate("PlotXYDemo", "\345\260\206\347\273\230\345\233\276\347\275\256\344\272\216\346\234\200\344\270\212", Q_NULLPTR));
        actionSend_To_Back_Ctrl->setText(QApplication::translate("PlotXYDemo", "\345\260\206\347\273\230\345\233\276\347\275\256\344\272\216\346\234\200\345\220\216", Q_NULLPTR));
        actionBring_Forward->setText(QApplication::translate("PlotXYDemo", "Bring Forward       +", Q_NULLPTR));
        actionSend_Backward->setText(QApplication::translate("PlotXYDemo", "Send Backward", Q_NULLPTR));
        actionTile_Horizontally->setText(QApplication::translate("PlotXYDemo", "Tile Horizontally", Q_NULLPTR));
        actionTile_Vertically->setText(QApplication::translate("PlotXYDemo", "Tile Vertically", Q_NULLPTR));
        actionSave_Screenshot->setText(QApplication::translate("PlotXYDemo", "\344\277\235\345\255\230\346\210\252\345\233\276", Q_NULLPTR));
        actionQuit->setText(QApplication::translate("PlotXYDemo", "\351\200\200\345\207\272                                     Alt+Q", Q_NULLPTR));
        action1->setText(QApplication::translate("PlotXYDemo", "1", Q_NULLPTR));
        action2->setText(QApplication::translate("PlotXYDemo", "2", Q_NULLPTR));
        action3->setText(QApplication::translate("PlotXYDemo", "3", Q_NULLPTR));
        action4->setText(QApplication::translate("PlotXYDemo", "4", Q_NULLPTR));
        action5->setText(QApplication::translate("PlotXYDemo", "5", Q_NULLPTR));
        action6->setText(QApplication::translate("PlotXYDemo", "6", Q_NULLPTR));
        action7->setText(QApplication::translate("PlotXYDemo", "7", Q_NULLPTR));
        action8->setText(QApplication::translate("PlotXYDemo", "8", Q_NULLPTR));
        action9->setText(QApplication::translate("PlotXYDemo", "9", Q_NULLPTR));
        action10->setText(QApplication::translate("PlotXYDemo", "10", Q_NULLPTR));
        actionClear_recent_files->setText(QApplication::translate("PlotXYDemo", "Clear recent files", Q_NULLPTR));
        action1_2->setText(QApplication::translate("PlotXYDemo", "1", Q_NULLPTR));
        action2_2->setText(QApplication::translate("PlotXYDemo", "2", Q_NULLPTR));
        action3_2->setText(QApplication::translate("PlotXYDemo", "3", Q_NULLPTR));
        action4_2->setText(QApplication::translate("PlotXYDemo", "4", Q_NULLPTR));
        action5_2->setText(QApplication::translate("PlotXYDemo", "5", Q_NULLPTR));
        action6_2->setText(QApplication::translate("PlotXYDemo", "6", Q_NULLPTR));
        action7_2->setText(QApplication::translate("PlotXYDemo", "7", Q_NULLPTR));
        action8_2->setText(QApplication::translate("PlotXYDemo", "8", Q_NULLPTR));
        action9_2->setText(QApplication::translate("PlotXYDemo", "9", Q_NULLPTR));
        action10_2->setText(QApplication::translate("PlotXYDemo", "10", Q_NULLPTR));
        actionClear_recent_files_2->setText(QApplication::translate("PlotXYDemo", "Clear recent files", Q_NULLPTR));
        actionPlot_Wizard->setText(QApplication::translate("PlotXYDemo", "\347\273\230\345\233\276\345\220\221\345\257\274", Q_NULLPTR));
        actionPlot_Manager_Ctrl_M->setText(QApplication::translate("PlotXYDemo", "\345\233\276\350\241\250\347\256\241\347\220\206\345\231\250", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        actionPlot_Manager_Ctrl_M->setToolTip(QApplication::translate("PlotXYDemo", "\345\233\276\350\241\250\347\256\241\347\220\206\345\231\250", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        actionWidget_Editor->setText(QApplication::translate("PlotXYDemo", "\346\216\247\344\273\266\347\274\226\350\276\221...", Q_NULLPTR));
        actionExport_to_GOG->setText(QApplication::translate("PlotXYDemo", "\345\257\274\345\207\272 GOG...", Q_NULLPTR));
        actionCreate_Plot->setText(QApplication::translate("PlotXYDemo", "\345\210\233\345\273\272\347\273\230\345\233\276", Q_NULLPTR));
        actionAutofit->setText(QApplication::translate("PlotXYDemo", "\350\207\252\345\212\250\351\200\202\345\272\224\345\244\247\345\260\217", Q_NULLPTR));
        actionOne_To_One->setText(QApplication::translate("PlotXYDemo", "One-To-One", Q_NULLPTR));
        actionRound_Ranges->setText(QApplication::translate("PlotXYDemo", "Round Ranges", Q_NULLPTR));
        actionLock_Data_Display->setText(QApplication::translate("PlotXYDemo", "\351\224\201\345\256\232\345\261\225\347\244\272", Q_NULLPTR));
        actionLock_Stacking_Order->setText(QApplication::translate("PlotXYDemo", "Lock Stacking Order", Q_NULLPTR));
        actionInvert_Colores->setText(QApplication::translate("PlotXYDemo", "Invert Colors", Q_NULLPTR));
        actionAdvanced_Data_Manager->setText(QApplication::translate("PlotXYDemo", "\351\253\230\347\272\247\346\225\260\346\215\256\347\256\241\347\220\206", Q_NULLPTR));
        actionAdd_Plot_Pair_Ctrl_A->setText(QApplication::translate("PlotXYDemo", "\346\267\273\345\212\240\346\225\260\346\215\256\345\257\271", Q_NULLPTR));
        actionDiscovery_Rules->setText(QApplication::translate("PlotXYDemo", "Discovery Rules...", Q_NULLPTR));
        actionShow_Object_Aliases_Ctrl_Alt_A->setText(QApplication::translate("PlotXYDemo", "Show Object Aliases Ctrl+Alt+A", Q_NULLPTR));
        actionReference_Points_Ctrl_R->setText(QApplication::translate("PlotXYDemo", "Reference Points...   Ctrl+R", Q_NULLPTR));
        actionEntity_Status_Ctrl_Alt_S->setText(QApplication::translate("PlotXYDemo", "Entity Status...   Ctrl+Alt+S", Q_NULLPTR));
        actionClassification->setText(QApplication::translate("PlotXYDemo", "Classification...", Q_NULLPTR));
        actionPlay->setText(QApplication::translate("PlotXYDemo", "\346\222\255\346\224\276        P", Q_NULLPTR));
        actionReverse->setText(QApplication::translate("PlotXYDemo", "\345\200\222\346\224\276    Ctrl+D", Q_NULLPTR));
        actionReal_Time->setText(QApplication::translate("PlotXYDemo", "\346\255\243\345\270\270\345\200\215\351\200\237     Shift+R", Q_NULLPTR));
        actionTime_Controls->setText(QApplication::translate("PlotXYDemo", "\346\227\266\351\227\264\346\216\247\345\210\266    Alt+T", Q_NULLPTR));
        actionTime_Client->setText(QApplication::translate("PlotXYDemo", "Time Client    Alt+X", Q_NULLPTR));
        actionTime_Server->setText(QApplication::translate("PlotXYDemo", "Time Server    Shift+X", Q_NULLPTR));
        actionNew_Tab_Ctrl_T->setText(QApplication::translate("PlotXYDemo", "\346\226\260\345\273\272\346\240\207\347\255\276            Ctrl+T", Q_NULLPTR));
        actionRename_Tab->setText(QApplication::translate("PlotXYDemo", "\351\207\215\345\221\275\345\220\215\346\240\207\347\255\276...", Q_NULLPTR));
        actionClose_Tab->setText(QApplication::translate("PlotXYDemo", "\345\205\263\351\227\255\346\240\207\347\255\276    Ctrl+F4", Q_NULLPTR));
        actionNext_Tab_Ctrl_Tab->setText(QApplication::translate("PlotXYDemo", "\345\210\207\346\215\242\344\270\213\344\270\200\344\270\252\346\240\207\347\255\276\351\241\265          Ctrl+Tab", Q_NULLPTR));
        actionPrevious_Tab_Ctrl_Shift_Tab->setText(QApplication::translate("PlotXYDemo", "\345\210\207\346\215\242\344\270\212\344\270\200\344\270\252 \346\240\207\347\255\276\351\241\265     Ctrl+Shift+Tab", Q_NULLPTR));
        actionShow_Menubar_Ctrl_Alt_M->setText(QApplication::translate("PlotXYDemo", "\346\230\276\347\244\272\350\217\234\345\215\225\346\240\217    Ctrl+Alt+M", Q_NULLPTR));
        actionShow_Toolbar_Ctrl_Alt_C->setText(QApplication::translate("PlotXYDemo", "\346\230\276\347\244\272\345\267\245\345\205\267\346\240\217     Ctrl+Alt+C", Q_NULLPTR));
        actionShow_Statusbar_Ctrl_Alt_B->setText(QApplication::translate("PlotXYDemo", "\346\230\276\347\244\272\347\212\266\346\200\201\346\240\217   Ctrl+Alt+B", Q_NULLPTR));
        actionShow_Time_Slider->setText(QApplication::translate("PlotXYDemo", "\346\230\276\347\244\272\346\227\266\351\227\264\350\275\264", Q_NULLPTR));
        actionShow_Tabbar->setText(QApplication::translate("PlotXYDemo", "\346\230\276\347\244\272\346\240\207\347\255\276\346\240\217", Q_NULLPTR));
        actionShow_RTI_Controls->setText(QApplication::translate("PlotXYDemo", "\346\230\276\347\244\272RTI\346\216\247\345\210\266", Q_NULLPTR));
        actionShow_All_Bars_Ctrl_B->setText(QApplication::translate("PlotXYDemo", "\346\230\276\347\244\272\346\211\200\346\234\211\346\240\217       Ctrl+B", Q_NULLPTR));
        actionShow_Plot_Time_Ctrl_Alt_P->setText(QApplication::translate("PlotXYDemo", "\346\230\276\347\244\272\347\273\230\345\233\276\344\270\255\346\227\266\351\227\264   Ctrl+Alt+P", Q_NULLPTR));
        actionShow_System_Time_Ctrl_Alt_Y->setText(QApplication::translate("PlotXYDemo", "\346\230\276\347\244\272\347\263\273\347\273\237\346\227\266\351\227\264  Ctrl+Alt+Y", Q_NULLPTR));
        actionShow_Corner_Logo->setText(QApplication::translate("PlotXYDemo", "\346\230\276\347\244\272Logo", Q_NULLPTR));
        actionShow_Frame_Rate_Alt_F->setText(QApplication::translate("PlotXYDemo", "Show Frame Rate     Alt+F", Q_NULLPTR));
        actionFullScreen_Shift_F->setText(QApplication::translate("PlotXYDemo", "\345\205\250\345\261\217\346\230\276\347\244\272    Shift+F", Q_NULLPTR));
        actionSave_Preferences->setText(QApplication::translate("PlotXYDemo", "Save Preferences", Q_NULLPTR));
        actionSave_Preferences_As->setText(QApplication::translate("PlotXYDemo", "Save Preferences As...", Q_NULLPTR));
        actionLoad_Preferences->setText(QApplication::translate("PlotXYDemo", "Load Preferences...", Q_NULLPTR));
        actionUseer_Functions->setText(QApplication::translate("PlotXYDemo", "Useer Functions...", Q_NULLPTR));
        actionFunction_Console->setText(QApplication::translate("PlotXYDemo", "Function Console...", Q_NULLPTR));
        actionHot_Keys_Ctrl_H->setText(QApplication::translate("PlotXYDemo", "Hot Keys...    Ctrl+H", Q_NULLPTR));
        actionOptions_Ctrl_Alt_O->setText(QApplication::translate("PlotXYDemo", "Options...   Ctrl+Alt+O", Q_NULLPTR));
        actionPlug_in_Manager->setText(QApplication::translate("PlotXYDemo", "Plug-in Manager...", Q_NULLPTR));
        actionConsole_Ctrl_F1->setText(QApplication::translate("PlotXYDemo", "Console...   Ctrl+F1", Q_NULLPTR));
        actionFind_DCS_Sever->setText(QApplication::translate("PlotXYDemo", "Find DCS Sever...", Q_NULLPTR));
        actionHDF5_Export->setText(QApplication::translate("PlotXYDemo", "HDF5 Export...", Q_NULLPTR));
        actionHDF5_Import->setText(QApplication::translate("PlotXYDemo", "HDF5 Import...", Q_NULLPTR));
        actionSimple_Sever->setText(QApplication::translate("PlotXYDemo", "Simple Sever...", Q_NULLPTR));
        actionSp_Batch_Loader->setText(QApplication::translate("PlotXYDemo", "Sp Batch Loader...", Q_NULLPTR));
        actionsimVideo_Recorder->setText(QApplication::translate("PlotXYDemo", "simVideo Recorder...", Q_NULLPTR));
        actionUser_Manual_F1->setText(QApplication::translate("PlotXYDemo", "User Manual    F1", Q_NULLPTR));
        actionTraining->setText(QApplication::translate("PlotXYDemo", "Training...", Q_NULLPTR));
        actionAbout->setText(QApplication::translate("PlotXYDemo", "About", Q_NULLPTR));
        actionSave_Snapshot->setText(QApplication::translate("PlotXYDemo", "Save Snapshot", Q_NULLPTR));
        actionRun_Python_Script_Ctrl_E->setText(QApplication::translate("PlotXYDemo", "\350\277\220\350\241\214 Python Script          Ctrl+E", Q_NULLPTR));
        actionDecrease_Step->setText(QApplication::translate("PlotXYDemo", "Decrease Step", Q_NULLPTR));
        actionFrame_Rverse->setText(QApplication::translate("PlotXYDemo", "Frame Reverse", Q_NULLPTR));
        actionStop->setText(QApplication::translate("PlotXYDemo", "Stop", Q_NULLPTR));
        actionFrame_Forward->setText(QApplication::translate("PlotXYDemo", "Frame Forward", Q_NULLPTR));
        actionIncrease_Step->setText(QApplication::translate("PlotXYDemo", "Increase Step", Q_NULLPTR));
        actionselect_plot->setText(QApplication::translate("PlotXYDemo", "select plot", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("PlotXYDemo", "Tab 1", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("PlotXYDemo", "Tab 2", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("PlotXYDemo", "Tab 3", Q_NULLPTR));
        menufile->setTitle(QApplication::translate("PlotXYDemo", "\346\226\207\344\273\266", Q_NULLPTR));
        menuRecent_Files->setTitle(QApplication::translate("PlotXYDemo", "\346\234\200\350\277\221\346\211\223\345\274\200\347\232\204\346\226\207\344\273\266", Q_NULLPTR));
        menuRecent_PMLs->setTitle(QApplication::translate("PlotXYDemo", "\346\234\200\350\277\221\346\211\223\345\274\200\347\232\204PML ", Q_NULLPTR));
        menuEdit->setTitle(QApplication::translate("PlotXYDemo", "\347\274\226\350\276\221", Q_NULLPTR));
        menuOrder->setTitle(QApplication::translate("PlotXYDemo", "\346\216\222\345\272\217", Q_NULLPTR));
        menuGraph->setTitle(QApplication::translate("PlotXYDemo", "\345\233\276\345\261\202", Q_NULLPTR));
        menuData->setTitle(QApplication::translate("PlotXYDemo", "\346\225\260\346\215\256", Q_NULLPTR));
        menuTime->setTitle(QApplication::translate("PlotXYDemo", "\346\227\266\351\227\264", Q_NULLPTR));
        menuTabs->setTitle(QApplication::translate("PlotXYDemo", "\346\240\207\347\255\276", Q_NULLPTR));
        menuView->setTitle(QApplication::translate("PlotXYDemo", "\350\247\206\345\233\276", Q_NULLPTR));
        menuTools->setTitle(QApplication::translate("PlotXYDemo", " \345\267\245\345\205\267", Q_NULLPTR));
        menuBookmarks->setTitle(QApplication::translate("PlotXYDemo", "\345\270\256\345\212\251", Q_NULLPTR));
        menuPlug_ins->setTitle(QApplication::translate("PlotXYDemo", " \346\217\222\344\273\266", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class PlotXYDemo: public Ui_PlotXYDemo {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PLOTXYDEMO_H
